apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kibana-logging
  namespace: logging
  labels:
    k8s-app: kibana-logging
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: kibana-logging
  template:
    metadata:
      labels:
        k8s-app: kibana-logging
    spec:
      containers:
      - name: kibana-logging
        image: kibana:7.6.1
        resources:
         # need more cpu upon initialization, therefore burstable class
         limits:
           cpu: 1000m
         requests:
           cpu: 100m
        env:
          - name: "CLUSTER_NAME"
            value: "myesdb"
          - name: ELASTICSEARCH_URL
            value: http://elasticsearch:9200
          - name: XPACK_MONITORING_ENABLED
            value: "false"
          - name: XPACK_SECURITY_ENABLED
            value: "false"
          - name: XPACK_REPORTING_ENABLED
            value: "false"
          - name: XPACK_ML_ENABLED
            value: "false"   
          - name: XPACK_GRAPH_ENABLED
            value: "false"    
        ports:
        - containerPort: 5601
          name: ui
          protocol: TCP
