apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: logging
  labels:
    component: elk
    role: kibana
spec:
  selector:
    k8s-app: kibana-logging
  ports:
  - name: http
    port: 80
    targetPort: 5601
    protocol: TCP
